version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./client # path to dockerfile
    ports: # Port binding to host from docker container
      - "80:80" # Bind port 3000 of host to 3000 of container
    container_name: chatty-client
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./server
    ports:
      - "8000:8000"
    container_name: chatty-server
    restart: always

